//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Landmark {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Landmark() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Landmark", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///
        ///&lt;table&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Title:&lt;/td&gt;
        ///&lt;td&gt;{{Title}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;First Name:&lt;/td&gt;
        ///&lt;td&gt;{{FirstName}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Last Name:&lt;/td&gt;
        ///&lt;td&gt;{{LastName}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Telephone:&lt;/td&gt;
        ///&lt;td&gt;{{Telephone}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Email:&lt;/td&gt;
        ///&lt;td&gt;{{Email}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Enquiry Type:&lt;/td&gt;
        ///&lt;td&gt;{{EnquiryType}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Message:&lt;/td&gt;
        ///&lt;td&gt;{{Message}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/table&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ContactUsForm {
            get {
                return ResourceManager.GetString("ContactUsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF-Afghanistan-阿富汗-阿富汗
        ///AL-Albania-阿爾巴尼亞-阿尔巴尼亚
        ///DZ-Algeria-阿爾及利亞-阿尔及利亚
        ///AS-American Samoa-薩摩亞（美）-萨摩亚（美）
        ///AD-Andorra-安道爾-安道尔
        ///AO-Angola-安哥拉-安哥拉
        ///AI-Anguilla-安圭拉-安圭拉
        ///AQ-Antarctica-南極洲-南极洲
        ///AG-Antigua and Barbuda-安提瓜和巴布達-安提瓜和巴布达
        ///AR-Argentina-阿根廷-阿根廷
        ///AM-Armenia-亞美尼亞-亚美尼亚
        ///AW-Aruba-阿魯巴-阿鲁巴
        ///AU-Australia-澳大利亞-澳大利亚
        ///AT-Austria-奧地利-奥地利
        ///AZ-Azerbaijan-阿塞拜疆-阿塞拜疆
        ///BS-Bahamas-巴哈馬-巴哈马
        ///BH-Bahrain-巴林-巴林
        ///BD-Bangladesh-孟加拉-孟加拉
        ///BB-Barbados-巴巴多斯-巴巴多斯
        ///BY-Belarus-白俄羅斯-白俄罗斯
        ///BE-Belgium-比利時-比利时
        ///BZ-Belize-伯利茲-伯利兹
        ///BJ-Benin [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountryList {
            get {
                return ResourceManager.GetString("CountryList", resourceCulture);
            }
        }
    }
}
