//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Landmark {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Landmark() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Landmark", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;
        ///&lt;html&gt;
        ///&lt;body&gt;
        ///
        ///&lt;table&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Title:&lt;/td&gt;
        ///&lt;td&gt;{{Title}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;First Name:&lt;/td&gt;
        ///&lt;td&gt;{{FirstName}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Last Name:&lt;/td&gt;
        ///&lt;td&gt;{{LastName}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Telephone:&lt;/td&gt;
        ///&lt;td&gt;{{Telephone}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Email:&lt;/td&gt;
        ///&lt;td&gt;{{Email}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Enquiry Type:&lt;/td&gt;
        ///&lt;td&gt;{{EnquiryType}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;tr&gt;
        ///&lt;td&gt;Message:&lt;/td&gt;
        ///&lt;td&gt;{{Message}}&lt;/td&gt;
        ///&lt;/tr&gt;
        ///&lt;/table&gt;
        ///
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string ContactUsForm {
            get {
                return ResourceManager.GetString("ContactUsForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AF Afghanistan
        ///AX Aland Islands
        ///AL Albania
        ///DZ Algeria
        ///AS American Samoa
        ///AD Andorra
        ///AO Angola
        ///AI Anguilla/St Kitts
        ///AQ Antarctica
        ///AG Antigua and Barbuda
        ///AR Argentina
        ///AM Armenia
        ///AW Aruba
        ///AU Australia
        ///AT Austria
        ///AZ Azerbaijan
        ///BS Bahamas
        ///BH Bahrain
        ///BD Bangladesh
        ///BB Barbados
        ///BY Belarus
        ///BE Belgium
        ///BZ Belize
        ///BJ Benin
        ///BM Bermuda
        ///BT Bhutan
        ///BO Bolivia
        ///BQ Bonaire,Saba,St Eustatius
        ///BA Bosnia And Herzegovina
        ///BW Botswna
        ///BV Bouvet Island
        ///BR Brazil
        ///IO British Indian Ocean Territory
        ///BN Brunei [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CountryList {
            get {
                return ResourceManager.GetString("CountryList", resourceCulture);
            }
        }
    }
}
