//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Landmark.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailSignup
    {
        public System.Guid ID { get; set; }
        public string Title { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Channel { get; set; }
        public string Interest { get; set; }
        public string Room { get; set; }
        public string Building { get; set; }
        public string Street { get; set; }
        public string Area { get; set; }
        public string District { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Postcode { get; set; }
        public string Country { get; set; }
        public string IpAddress { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> OptIn { get; set; }
    }
}
