// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;

namespace Sitecore.CodeGeneration
{
  #region Designer generated code

    public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

		[SitecoreInfo(SitecoreInfoType.Name)]
		string Name { get; set; }
	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Name)]
		public virtual string Name { get; set; }

		[SitecoreInfo(SitecoreInfoType.FullPath)]
		public virtual string Path { get; set; }
	}

  
  [SitecoreType(TemplateId="e2145f3b-75a1-4622-b747-1a231771a499")]
  public interface IBaseItem {
  [SitecoreField("Title")]
  string Title {get; set;}
  [SitecoreField("Description")]
  string Description {get; set;}
  }
  
  [SitecoreType(TemplateId="440c78f9-3de9-49fc-b846-ca918e18d8b4")]
  public interface IDocumentItem : IBaseItem {
  [SitecoreField("Author")]
  string Author {get; set;}
  }
  
  [SitecoreType(TemplateId="4c0ba879-87e2-4b01-856f-19d85bd3a7c9")]
  public interface IHomePage : IBaseItem {
  [SitecoreField("Image")]
  Image Image {get; set;}
  [SitecoreField("Call to Action Text")]
  string CallToActionText {get; set;}
  [SitecoreField("Call to Action Link")]
  Link CallToActionLink {get; set;}
  }
  
  /// <summary>
  /// Represents the strongly named BaseItem class.
  /// </summary>
[SitecoreType(TemplateId="e2145f3b-75a1-4622-b747-1a231771a499")]
  public partial class BaseItem : GlassBase, IBaseItem {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [SitecoreField("Title")]
      public virtual string Title {get; set;}
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [SitecoreField("Description")]
      public virtual string Description {get; set;}
  }
  
  /// <summary>
  /// Represents the strongly named DocumentItem class.
  /// </summary>
[SitecoreType(TemplateId="440c78f9-3de9-49fc-b846-ca918e18d8b4")]
  public partial class DocumentItem : GlassBase, IDocumentItem {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [SitecoreField("Author")]
      public virtual string Author {get; set;}
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    string IBaseItem.Title {get; set;}
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    string IBaseItem.Description {get; set;}
  }
  
  /// <summary>
  /// Represents the strongly named HomePage class.
  /// </summary>
[SitecoreType(TemplateId="4c0ba879-87e2-4b01-856f-19d85bd3a7c9")]
  public partial class HomePage : GlassBase, IHomePage {
    
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [SitecoreField("Image")]
      public virtual Image Image {get; set;}
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [SitecoreField("Call to Action Text")]
      public virtual string CallToActionText {get; set;}
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [SitecoreField("Call to Action Link")]
      public virtual Link CallToActionLink {get; set;}
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    string IBaseItem.Title {get; set;}
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    string IBaseItem.Description {get; set;}
  }
     
  #endregion
}

#pragma warning restore 1591