// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Sitecore.CodeGeneration
{
  #region Designer generated code

  
   /// <summary>
   /// Represents the strongly named ProfileCardValueField class.
   /// </summary>
   public partial class ProfileCardValueField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public ProfileCardValueField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator ProfileCardValueField(string value) {
      return value == null ? null : new ProfileCardValueField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(ProfileCardValueField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named ProfileCardsField class.
   /// </summary>
   public partial class ProfileCardsField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public ProfileCardsField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator ProfileCardsField(string value) {
      return value == null ? null : new ProfileCardsField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(ProfileCardsField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named TrackingField class.
   /// </summary>
   public partial class TrackingField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public TrackingField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator TrackingField(string value) {
      return value == null ? null : new TrackingField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(TrackingField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named CheckboxField class.
   /// </summary>
   public partial class CheckboxField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public CheckboxField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator CheckboxField(string value) {
      return value == null ? null : new CheckboxField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(CheckboxField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named DateField class.
   /// </summary>
   public partial class DateField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public DateField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator DateField(string value) {
      return value == null ? null : new DateField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(DateField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named DatetimeField class.
   /// </summary>
   public partial class DatetimeField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public DatetimeField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator DatetimeField(string value) {
      return value == null ? null : new DatetimeField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(DatetimeField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named FileField class.
   /// </summary>
   public partial class FileField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public FileField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator FileField(string value) {
      return value == null ? null : new FileField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(FileField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named ImageField class.
   /// </summary>
   public partial class ImageField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public ImageField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator ImageField(string value) {
      return value == null ? null : new ImageField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(ImageField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named IntegerField class.
   /// </summary>
   public partial class IntegerField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public IntegerField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator IntegerField(string value) {
      return value == null ? null : new IntegerField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(IntegerField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named MultiLineTextField class.
   /// </summary>
   public partial class MultiLineTextField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public MultiLineTextField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator MultiLineTextField(string value) {
      return value == null ? null : new MultiLineTextField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(MultiLineTextField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named NumberField class.
   /// </summary>
   public partial class NumberField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public NumberField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator NumberField(string value) {
      return value == null ? null : new NumberField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(NumberField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named PasswordField class.
   /// </summary>
   public partial class PasswordField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public PasswordField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator PasswordField(string value) {
      return value == null ? null : new PasswordField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(PasswordField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named RichTextField class.
   /// </summary>
   public partial class RichTextField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public RichTextField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator RichTextField(string value) {
      return value == null ? null : new RichTextField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(RichTextField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named SingleLineTextField class.
   /// </summary>
   public partial class SingleLineTextField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public SingleLineTextField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator SingleLineTextField(string value) {
      return value == null ? null : new SingleLineTextField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(SingleLineTextField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named WordDocumentField class.
   /// </summary>
   public partial class WordDocumentField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public WordDocumentField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator WordDocumentField(string value) {
      return value == null ? null : new WordDocumentField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(WordDocumentField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named ChecklistField class.
   /// </summary>
   public partial class ChecklistField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public ChecklistField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator ChecklistField(string value) {
      return value == null ? null : new ChecklistField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(ChecklistField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named DroplistField class.
   /// </summary>
   public partial class DroplistField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public DroplistField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator DroplistField(string value) {
      return value == null ? null : new DroplistField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(DroplistField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named GroupedDroplinkField class.
   /// </summary>
   public partial class GroupedDroplinkField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public GroupedDroplinkField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator GroupedDroplinkField(string value) {
      return value == null ? null : new GroupedDroplinkField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(GroupedDroplinkField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named GroupedDroplistField class.
   /// </summary>
   public partial class GroupedDroplistField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public GroupedDroplistField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator GroupedDroplistField(string value) {
      return value == null ? null : new GroupedDroplistField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(GroupedDroplistField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named MultilistField class.
   /// </summary>
   public partial class MultilistField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public MultilistField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator MultilistField(string value) {
      return value == null ? null : new MultilistField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(MultilistField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named MultilistWithSearchField class.
   /// </summary>
   public partial class MultilistWithSearchField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public MultilistWithSearchField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator MultilistWithSearchField(string value) {
      return value == null ? null : new MultilistWithSearchField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(MultilistWithSearchField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named NameLookupValueListField class.
   /// </summary>
   public partial class NameLookupValueListField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public NameLookupValueListField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator NameLookupValueListField(string value) {
      return value == null ? null : new NameLookupValueListField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(NameLookupValueListField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named NameValueListField class.
   /// </summary>
   public partial class NameValueListField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public NameValueListField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator NameValueListField(string value) {
      return value == null ? null : new NameValueListField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(NameValueListField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named TreelistField class.
   /// </summary>
   public partial class TreelistField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public TreelistField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator TreelistField(string value) {
      return value == null ? null : new TreelistField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(TreelistField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named TreelistWithSearchField class.
   /// </summary>
   public partial class TreelistWithSearchField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public TreelistWithSearchField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator TreelistWithSearchField(string value) {
      return value == null ? null : new TreelistWithSearchField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(TreelistWithSearchField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named TreelistExField class.
   /// </summary>
   public partial class TreelistExField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public TreelistExField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator TreelistExField(string value) {
      return value == null ? null : new TreelistExField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(TreelistExField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named DroplinkField class.
   /// </summary>
   public partial class DroplinkField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public DroplinkField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator DroplinkField(string value) {
      return value == null ? null : new DroplinkField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(DroplinkField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named DroptreeField class.
   /// </summary>
   public partial class DroptreeField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public DroptreeField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator DroptreeField(string value) {
      return value == null ? null : new DroptreeField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(DroptreeField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named GeneralLinkField class.
   /// </summary>
   public partial class GeneralLinkField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public GeneralLinkField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator GeneralLinkField(string value) {
      return value == null ? null : new GeneralLinkField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(GeneralLinkField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named GeneralLinkWithSearchField class.
   /// </summary>
   public partial class GeneralLinkWithSearchField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public GeneralLinkWithSearchField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator GeneralLinkWithSearchField(string value) {
      return value == null ? null : new GeneralLinkWithSearchField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(GeneralLinkWithSearchField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named VersionLinkField class.
   /// </summary>
   public partial class VersionLinkField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public VersionLinkField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator VersionLinkField(string value) {
      return value == null ? null : new VersionLinkField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(VersionLinkField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named IconField class.
   /// </summary>
   public partial class IconField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public IconField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator IconField(string value) {
      return value == null ? null : new IconField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(IconField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named IFrameField class.
   /// </summary>
   public partial class IFrameField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public IFrameField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator IFrameField(string value) {
      return value == null ? null : new IFrameField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(IFrameField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named TristateField class.
   /// </summary>
   public partial class TristateField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public TristateField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator TristateField(string value) {
      return value == null ? null : new TristateField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(TristateField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named AttachmentField class.
   /// </summary>
   public partial class AttachmentField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public AttachmentField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator AttachmentField(string value) {
      return value == null ? null : new AttachmentField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(AttachmentField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named CustomField class.
   /// </summary>
   public partial class CustomField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public CustomField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator CustomField(string value) {
      return value == null ? null : new CustomField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(CustomField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named DatasourceField class.
   /// </summary>
   public partial class DatasourceField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public DatasourceField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator DatasourceField(string value) {
      return value == null ? null : new DatasourceField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(DatasourceField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named FileDropAreaField class.
   /// </summary>
   public partial class FileDropAreaField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public FileDropAreaField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator FileDropAreaField(string value) {
      return value == null ? null : new FileDropAreaField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(FileDropAreaField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named InternalLinkField class.
   /// </summary>
   public partial class InternalLinkField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public InternalLinkField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator InternalLinkField(string value) {
      return value == null ? null : new InternalLinkField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(InternalLinkField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named LayoutField class.
   /// </summary>
   public partial class LayoutField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public LayoutField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator LayoutField(string value) {
      return value == null ? null : new LayoutField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(LayoutField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named PagePreviewField class.
   /// </summary>
   public partial class PagePreviewField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public PagePreviewField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator PagePreviewField(string value) {
      return value == null ? null : new PagePreviewField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(PagePreviewField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named QueryBuilderField class.
   /// </summary>
   public partial class QueryBuilderField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public QueryBuilderField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator QueryBuilderField(string value) {
      return value == null ? null : new QueryBuilderField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(QueryBuilderField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named QueryDatasourceField class.
   /// </summary>
   public partial class QueryDatasourceField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public QueryDatasourceField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator QueryDatasourceField(string value) {
      return value == null ? null : new QueryDatasourceField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(QueryDatasourceField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named RenderingDatasourceField class.
   /// </summary>
   public partial class RenderingDatasourceField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public RenderingDatasourceField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator RenderingDatasourceField(string value) {
      return value == null ? null : new RenderingDatasourceField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(RenderingDatasourceField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named RulesField class.
   /// </summary>
   public partial class RulesField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public RulesField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator RulesField(string value) {
      return value == null ? null : new RulesField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(RulesField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named SecurityField class.
   /// </summary>
   public partial class SecurityField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public SecurityField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator SecurityField(string value) {
      return value == null ? null : new SecurityField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(SecurityField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named TemplateFieldSourceField class.
   /// </summary>
   public partial class TemplateFieldSourceField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public TemplateFieldSourceField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator TemplateFieldSourceField(string value) {
      return value == null ? null : new TemplateFieldSourceField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(TemplateFieldSourceField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named ThumbnailField class.
   /// </summary>
   public partial class ThumbnailField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public ThumbnailField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator ThumbnailField(string value) {
      return value == null ? null : new ThumbnailField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(ThumbnailField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named HtmlField class.
   /// </summary>
   public partial class HtmlField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public HtmlField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator HtmlField(string value) {
      return value == null ? null : new HtmlField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(HtmlField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named LinkField class.
   /// </summary>
   public partial class LinkField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public LinkField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator LinkField(string value) {
      return value == null ? null : new LinkField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(LinkField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named LookupField class.
   /// </summary>
   public partial class LookupField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public LookupField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator LookupField(string value) {
      return value == null ? null : new LookupField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(LookupField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named MemoField class.
   /// </summary>
   public partial class MemoField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public MemoField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator MemoField(string value) {
      return value == null ? null : new MemoField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(MemoField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named ReferenceField class.
   /// </summary>
   public partial class ReferenceField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public ReferenceField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator ReferenceField(string value) {
      return value == null ? null : new ReferenceField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(ReferenceField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named ServerFileField class.
   /// </summary>
   public partial class ServerFileField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public ServerFileField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator ServerFileField(string value) {
      return value == null ? null : new ServerFileField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(ServerFileField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named TextField class.
   /// </summary>
   public partial class TextField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public TextField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator TextField(string value) {
      return value == null ? null : new TextField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(TextField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named TreeField class.
   /// </summary>
   public partial class TreeField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public TreeField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator TreeField(string value) {
      return value == null ? null : new TreeField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(TreeField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named TreeListField class.
   /// </summary>
   public partial class TreeListField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public TreeListField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator TreeListField(string value) {
      return value == null ? null : new TreeListField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(TreeListField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
   /// <summary>
   /// Represents the strongly named ValuelookupField class.
   /// </summary>
   public partial class ValuelookupField {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public string Value { get; private set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public ValuelookupField(string value) {
      this.Value = value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator ValuelookupField(string value) {
      return value == null ? null : new ValuelookupField(value);
    } 

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator string(ValuelookupField field) {
      return field == null ? null : field.Value;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public override string ToString() {
      return this.Value;
    }
  }
  
  public interface IBaseItem {
  SingleLineTextField Title { get; }
  RichTextField Description { get; }
  }
  
  public interface IDocumentItem : IBaseItem {
  SingleLineTextField Author { get; }
  }
  
  public interface IHomePage : IBaseItem {
  ImageField Image { get; }
  SingleLineTextField CallToActionText { get; }
  GeneralLinkField CallToActionLink { get; }
  }
     

  /// <summary>
  /// Base class for the strongly typed template classes.
  /// </summary>
  public abstract partial class TemplateBase {
  }
  
  
  /// <summary>
  /// Represents the strongly named BaseItem class.
  /// </summary>
  public partial class BaseItem : TemplateBase, IBaseItem {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public Sitecore.Data.Items.Item InnerItem { get; set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public BaseItem(Sitecore.Data.Items.Item item) {
      this.InnerItem = item;  
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator BaseItem(Sitecore.Data.Items.Item item) {
      return item == null ? null : new BaseItem(item);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator Sitecore.Data.Items.Item(BaseItem item) {
      return item == null ? null : item.InnerItem;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]
      public SingleLineTextField Title { get { return new SingleLineTextField(this.InnerItem["{8FA39420-C203-4D59-8F86-8D48732E9959}"]); } }
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]
      public RichTextField Description { get { return new RichTextField(this.InnerItem["{4A4C6388-4745-477B-A61D-900351614444}"]); } }
  }
  
  /// <summary>
  /// Represents the strongly named DocumentItem class.
  /// </summary>
  public partial class DocumentItem : TemplateBase, IDocumentItem {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public Sitecore.Data.Items.Item InnerItem { get; set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public DocumentItem(Sitecore.Data.Items.Item item) {
      this.InnerItem = item;  
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator DocumentItem(Sitecore.Data.Items.Item item) {
      return item == null ? null : new DocumentItem(item);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator Sitecore.Data.Items.Item(DocumentItem item) {
      return item == null ? null : item.InnerItem;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]
      public SingleLineTextField Author { get { return new SingleLineTextField(this.InnerItem["{2531B20D-5947-4661-A7A0-53BA8C0FE9BB}"]); } }
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]
    SingleLineTextField IBaseItem.Title { get { return new SingleLineTextField(this.InnerItem["{8FA39420-C203-4D59-8F86-8D48732E9959}"]); } }
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]
    RichTextField IBaseItem.Description { get { return new RichTextField(this.InnerItem["{4A4C6388-4745-477B-A61D-900351614444}"]); } }
  }
  
  /// <summary>
  /// Represents the strongly named HomePage class.
  /// </summary>
  public partial class HomePage : TemplateBase, IHomePage {
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public Sitecore.Data.Items.Item InnerItem { get; set; }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public HomePage(Sitecore.Data.Items.Item item) {
      this.InnerItem = item;  
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator HomePage(Sitecore.Data.Items.Item item) {
      return item == null ? null : new HomePage(item);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]    
    public static implicit operator Sitecore.Data.Items.Item(HomePage item) {
      return item == null ? null : item.InnerItem;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]
      public ImageField Image { get { return new ImageField(this.InnerItem["{4DA238BA-A834-481D-8723-9F13F703B690}"]); } }
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]
      public SingleLineTextField CallToActionText { get { return new SingleLineTextField(this.InnerItem["{23DB2802-71B6-4D1E-A412-2D1DBE69EE79}"]); } }
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]
      public GeneralLinkField CallToActionLink { get { return new GeneralLinkField(this.InnerItem["{7ED6E19C-559C-49E5-BC97-270B222CDAEF}"]); } }
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]
    SingleLineTextField IBaseItem.Title { get { return new SingleLineTextField(this.InnerItem["{8FA39420-C203-4D59-8F86-8D48732E9959}"]); } }
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Sitecore Code Generator", "1.0.0.0")]
    RichTextField IBaseItem.Description { get { return new RichTextField(this.InnerItem["{4A4C6388-4745-477B-A61D-900351614444}"]); } }
  }
     
  #endregion
}

#pragma warning restore 1591