<%@ Page Language="C#" ClassName="CodeGenPage" %>
<%@ Import namespace="System.CodeDom.Compiler"  %>
<%@ Import Namespace="Sitecore" %>
<%@ Import Namespace="Sitecore.Data" %>
<%@ Import Namespace="Sitecore.Text" %>


// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

using System;   
using System.Collections.Generic;   
using System.Linq;
using System.Text;
using Glass.Mapper.Sc.Configuration.Attributes;
using Glass.Mapper.Sc.Configuration;
using Glass.Mapper.Sc.Fields;
using Sitecore.Globalization;
using Sitecore.Data;

namespace Sitecore.CodeGeneration
{
  #region Designer generated code

    public partial interface IGlassBase{
		
		[SitecoreId]
		Guid Id{ get; }

		[SitecoreInfo(SitecoreInfoType.Language)]
        Language Language{ get; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        int Version { get; }

		[SitecoreInfo(SitecoreInfoType.Name)]
		string Name { get; set; }
	}

	public abstract partial class GlassBase : IGlassBase{
		
		[SitecoreId]
		public virtual Guid Id{ get; private set;}

		[SitecoreInfo(SitecoreInfoType.Language)]
        public virtual Language Language{ get; private set; }

        [SitecoreInfo(SitecoreInfoType.Version)]
        public virtual int Version { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Url)]
        public virtual string Url { get; private set; }

		[SitecoreInfo(SitecoreInfoType.Name)]
		public virtual string Name { get; set; }

		[SitecoreInfo(SitecoreInfoType.FullPath)]
		public virtual string Path { get; set; }
	}

  <% foreach(var template in templates) { %>
  [SitecoreType(TemplateId="<%= template.Item.ID.ToGuid() %>")]
  public interface I<% =template.SafeName %><% =WriteBaseInterfaces(templates, template) %> {
  <% foreach(var field in template.Fields) { 
  %>[SitecoreField("<%= field.Name %>")]
  <% =GetGlassFieldType(field) %> <% =field.SafeName %> {get; set;}
  <% } %>}
  <% } %>   

  
  <% foreach(var template in templates) { %>
  /// <summary>
  /// Represents the strongly named <% =template.SafeName %> class.
  /// </summary>
[SitecoreType(TemplateId="<%= template.Item.ID.ToGuid() %>")]
  public partial class <% =template.SafeName %> : GlassBase, I<% =template.SafeName %> {
    
  <% foreach(var field in template.Fields) { 
  %>  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
      [SitecoreField("<%= field.Name %>")]
      public virtual <% =GetGlassFieldType(field) %> <% =field.SafeName %> {get; set;}
  <% } %>

  <% foreach(var field in template.GetInheritedFields()) { 
    %>  [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    <% =GetGlassFieldType(field) %> I<% =field.OwnerTemplate.SafeName %>.<% =field.SafeName %> {get; set;}
  <% } %>}
  <% } %>   
  #endregion
}

#pragma warning restore 1591

<script language="C#" runat="server"> 

  private readonly List<List<string>> scope = new List<List<string>>();
  private readonly List<Template> templates = new List<Template>();
  private readonly Dictionary<string, FieldType> fieldTypes = new Dictionary<string, FieldType>();
  private CodeDomProvider CodeDomProvider { get; set; }

  protected override void OnLoad(EventArgs e)
  {
    base.OnLoad(e);

    this.CodeDomProvider = CodeDomProvider.CreateProvider("C#");

    this.PushScope();
    
    var fieldTypesRoot = Sitecore.Context.Database.GetItem("/sitecore/system/field types");
    this.GetFieldTypes(this.fieldTypes, fieldTypesRoot);

    //string userDefinedTemplateRoot = ConfigurationManager.AppSettings["UserDefinedTemplateID"];
    string userDefinedTemplateRoot = "{B29EE504-861C-492F-95A3-0D890B6FCA09}";
    //var templateRoot = Sitecore.Context.ContentDatabase.GetItem(ItemIDs.TemplateRoot);
    var templateRoot = Sitecore.Context.ContentDatabase.GetItem(userDefinedTemplateRoot);
    this.GetTemplates(this.templates, templateRoot);

    foreach (var template in templates)
    {
      template.BuildBaseTemplates(template.Item);
    }
  }

  private void GetFieldTypes(Dictionary<string, FieldType> list, Sitecore.Data.Items.Item item)
  {
    if (item.TemplateID == TemplateIDs.TemplateFieldType)
    {
      var fieldType = new FieldType
      {
        Name = item.Name,
        SafeName = GetSafeName(scope, item.Name + "Field")
      };

      list[item.Name.ToLowerInvariant()] = fieldType;

      return;
    }

    foreach (Sitecore.Data.Items.Item child in item.Children)
    {
      GetFieldTypes(list, child);
    }
  }
  
  private void GetTemplates(List<Template> list, Sitecore.Data.Items.Item item)
  {
    if (item.TemplateID == TemplateIDs.Template)
    {
      var template = new Template(this)
      {
        Item = item,
        Name = item.Name,
        SafeName = GetSafeName(scope, item.Name)
      };
      
      list.Add(template);

      this.PushScope();
      scope[scope.Count - 1].Add(template.SafeName);
      scope[scope.Count - 1].Add("InnerItem");
      this.GetTemplateFields(template, item);
      this.PopScope();
      
      return;
    }

    foreach (Sitecore.Data.Items.Item child in item.Children)
    {
      GetTemplates(list, child);
    }
  }

  private void GetTemplateFields(Template template, Sitecore.Data.Items.Item item)
  {
    if (item.TemplateID == TemplateIDs.TemplateField)
    {
      var fieldType = item["Type"];
      if (string.IsNullOrEmpty(fieldType))
      {
        fieldType = "text";
      }
      
      var field = new Field(template.Page)
      {
        Item = item,
        OwnerTemplate = template,
        Name = item.Name,
        SafeName = GetSafeName(scope, item.Name),
        FieldType = fieldType
      };

      template.Fields.Add(field);

      return;
    }

    foreach (Sitecore.Data.Items.Item child in item.Children)
    {
      GetTemplateFields(template, child);
    }
  }

  private string GetSafeName(List<List<string>> scope, string name)
  {
    var safeName = name.Trim();
    if (safeName.StartsWith("__"))
    {
      safeName = safeName.Substring(2);
    }

    safeName = char.ToUpper(safeName[0]) + safeName.Substring(1);

    var n = safeName.IndexOf(' ');
    while (n >= 0)
    {
      safeName = safeName.Substring(0, n) + safeName.Substring(n + 1, 1).ToUpperInvariant() + safeName.Substring(n + 2);
      n = safeName.IndexOf(' ');
    }

    var regex = new Regex(@"[^\p{Ll}\p{Lu}\p{Lt}\p{Lo}\p{Nd}\p{Nl}\p{Mn}\p{Mc}\p{Cf}\p{Pc}\p{Lm}]");

    safeName = regex.Replace(safeName, string.Empty);
    if (safeName[0] != '_' && (!char.IsLetter(safeName, 0) || !CodeDomProvider.IsValidIdentifier(safeName)))
    {
      safeName = string.Concat("_", safeName);
    }

    var result = safeName;
    var index = 1;
    while (scope[scope.Count - 1].Contains(result))
    {
      index++;
      result = safeName + index;
    }

    scope[scope.Count - 1].Add(result);
    return result;
  }

  private void PushScope()
  {
    this.scope.Add(new List<string>());
  }

  private void PopScope()
  {
    this.scope.RemoveAt(this.scope.Count - 1);
  }

  public static string GetGlassFieldType(Field field)
  {
      if (field != null && field.FieldType != null)
      {
          switch (field.FieldType.ToLower())
          {
              case "tristate":
                  return "TriState";
              case "checkbox":
                  return "bool";

              case "date":
              case "datetime":
                  return "DateTime";

              case "number":
                  return "float";

              case "integer":
                  return "int";

              case "treelist with search":
              case "treelist":
              case "treelistex":
              case "treelist descriptive":
              case "checklist":
              case "multilist with search":
              case "multilist":
                  return string.Format("IEnumerable<{0}>", "Guid");

              case "grouped droplink":
              case "droplink":
              case "lookup":
              case "droptree":
              case "reference":
              case "tree":
                  return "Guid";

              case "file":
                  return "File";

              case "image selector":
                  return "IEnumerable<Image>";

              case "image":
                  return "Image";

              case "general link":
              case "general link with search":
                  return "Link";

              case "password":
              case "icon":
              case "rich text":
              case "html":
              case "single-line text":
              case "multi-line text":
              case "frame":
              case "text":
              case "memo":
              case "droplist":
              case "grouped droplist":
              case "valuelookup":
                  return "string";
              case "attachment":
              case "word document":
                  return "System.IO.Stream";
              case "name lookup value list":
              case "name value list":
                  return "System.Collections.Specialized.NameValueCollection";
              default:
                  return "object /* UNKNOWN */";
          }
      }
      else
      {
          throw new Exception("There is no 'Type' field on the " + field.Name + " field.");
      }
  }

  public string WriteBaseInterfaces(List<Template> templates, Template template)
  {
    var first = true;
    var result = new StringBuilder();
    
    foreach(var t in template.GetImmediateBaseTemplates())
    {
      result.Append(first ? " : " : ", ");
      first = false;

      result.Append("I" + t.SafeName);
    }

    return result.ToString();
  }
  
  public Template FindTemplate(ID id)
  {
    foreach (var template in templates)
    {
      if (template.Item.ID == id)
      {
        return template;
      }
    }

    return null;
  }

  public class Template
  {
    public Template(CodeGenPage page)
    {
      this.Page = page;
      this.Fields = new List<Field>();
      this.BaseTemplates = new List<Template>();
    }

    public CodeGenPage Page { get; set; }
    public Sitecore.Data.Items.Item Item { get; set; }
    public string Name { get; set; }
    public string SafeName { get; set; }
    public List<Field> Fields { get; set; }
    public List<Template> BaseTemplates { get; set; }

    public void BuildBaseTemplates(Sitecore.Data.Items.Item item)
    {
      var field = item[FieldIDs.BaseTemplate];
      if (string.IsNullOrEmpty(field))
      {
        return;
      }

      var listString = new ListString(field);
      foreach (var s in listString)
      {
        if (string.IsNullOrEmpty(s))
        {
          continue;
        }
        
        if (!Sitecore.Data.ID.IsID(s))
        {
          continue;
        }

        var id = new ID(s);
        var i = this.Page.FindTemplate(id);
        if (i == null) 
        {
          continue;
        }

        if (BaseTemplates.Contains(i))
        {
          continue;
        }
        
        BaseTemplates.Add(i);

        BuildBaseTemplates(i.Item);
      }
    }

    public List<Template> GetImmediateBaseTemplates()
    {
      var result = new List<Template>();

      var list = new ListString(Item[FieldIDs.BaseTemplate]);

      foreach (var s in list)
      {
        var id = new ID(s);
        var i = this.Page.FindTemplate(id);

        if (i != null)
        {
          result.Add(i);
        }
      }

      return result;
    }

    public List<Field> GetInheritedFields()
    {
      var result = new List<Field>();

      foreach (var baseTemplate in this.BaseTemplates)
      {
        foreach (var field in baseTemplate.Fields)
        {
          result.Add(field);
        }
      }

      return result;
    }    
  }
  
  public class Field
  {
    public Field(CodeGenPage page)
    {
      this.Page = page;
    }
  
    public CodeGenPage Page { get; set; }
    public Sitecore.Data.Items.Item Item { get; set; }
    public Template OwnerTemplate { get; set; }
    public string Name { get; set; }
    public string SafeName { get; set; }
    public string FieldType { get; set; }
    
    public FieldType GetFieldType()
    {
      FieldType result;
      if (!this.Page.fieldTypes.TryGetValue(this.FieldType.ToLowerInvariant(), out result))
      {
        this.Page.fieldTypes.TryGetValue("text", out result);
      }
      
      return result;
    }
  }

  public class FieldType
  {
    public string Name { get; set; }
    public string SafeName { get; set; }
  }
  
  </script>
