
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Landmark.Web
{
  #region Designer generated code

  using System;
  using Sitecore;
  using Sitecore.Diagnostics;
  using Sitecore.Data.Items;
  using Sitecore.Data.Fields;
  using Sitecore.Data;
  
  
    /**/
  /// <summary>Represents the "Document Item" template.</summary>
  public partial class DocumentItem : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{440C78F9-3DE9-49FC-B846-CA918E18D8B4}");

    public DocumentItem(Item item) : base(item) {
    }
    
    public static class FieldIds {
      
      public static readonly ID Author = ID.Parse("{2531B20D-5947-4661-A7A0-53BA8C0FE9BB}");

      public static readonly ID Date = ID.Parse("{9155B1E0-6456-4E1F-A0F3-92F47ED1E4C5}");

    }
    
    /// <summary>Gets or sets the "Author" field.</summary>
    public string Author 
    {
      get 
      {
        return this.InnerItem[FieldIds.Author];
      }
      set
      {
        this.InnerItem[FieldIds.Author] = value;
      }
    }
  
    /// <summary>Gets or sets the "Date" field.</summary>
    public string Date {
      get 
      {
        return this.InnerItem[FieldIds.Date];
      }
      set 
      {
        this.InnerItem[FieldIds.Date] = value;
      }
    }
  
    public static DocumentItem Create(Item item) 
    {
      return new DocumentItem(item);
    }

    public static implicit operator Item (DocumentItem item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator DocumentItem(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
  
    /**/
  /// <summary>Represents the "Home Page" template.</summary>
  public partial class HomePage : CustomItem
  {
    public static readonly ID TemplateID = ID.Parse("{4C0BA879-87E2-4B01-856F-19D85BD3A7C9}");

    public HomePage(Item item) : base(item) {
    }
    
    public static class FieldIds {
      
      public static readonly ID Image = ID.Parse("{4DA238BA-A834-481D-8723-9F13F703B690}");

      public static readonly ID CallToActionText = ID.Parse("{23DB2802-71B6-4D1E-A412-2D1DBE69EE79}");

      public static readonly ID CallToActionLink = ID.Parse("{7ED6E19C-559C-49E5-BC97-270B222CDAEF}");

    }
    
    /// <summary>Gets the "Image" field.</summary>
    public ImageField Image 
    {
      get 
      {
        return this.InnerItem.Fields[FieldIds.Image];
      }
    }
  
    /// <summary>Gets or sets the "Call to Action Text" field.</summary>
    public string CallToActionText 
    {
      get 
      {
        return this.InnerItem[FieldIds.CallToActionText];
      }
      set
      {
        this.InnerItem[FieldIds.CallToActionText] = value;
      }
    }
  
    /// <summary>Gets or sets the "Call to Action Link" field.</summary>
    public string CallToActionLink {
      get 
      {
        return this.InnerItem[FieldIds.CallToActionLink];
      }
      set 
      {
        this.InnerItem[FieldIds.CallToActionLink] = value;
      }
    }
  
    public static HomePage Create(Item item) 
    {
      return new HomePage(item);
    }

    public static implicit operator Item (HomePage item)
    {
      if (item == null)
      {
        return null;
      }

      return item.InnerItem;
    }

    public static explicit operator HomePage(Item item)
    {
      if (item == null)
      {
        return null;
      }

      if (item.TemplateID != TemplateID)
      {
        return null;
      }

      return Create(item);
    }
  }
  
  #endregion
}

#pragma warning restore 1591
